/*
 * Generated by ISE 16.05.9.8969 GPL Edition - macosx-x86-64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F293_6382();
extern void F297_6646();
extern void F291_6308();
extern void F296_6555();
extern void F421_4257();
extern void F337_6188();
extern void F66_1148();
extern EIF_REFERENCE F66_1135();
extern EIF_BOOLEAN F66_1147();
extern EIF_BOOLEAN F66_1152();
extern void F66_1157();
extern void F66_1158();
extern void F66_1159();
extern void F102_1639();
extern EIF_TYPED_VALUE F102_1640();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F293_6382;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F291_6308;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F421_4257;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F297_6646;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F296_6555;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F337_6188;
	egc_is_scoop_capable = 0;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F66_1148;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F66_1147;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F66_1135;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F66_1152;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F66_1157;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F66_1158;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F66_1159;

	egc_str_dtype = 296;

	egc_str32_dtype = 295;
	egc_arr_dtype = 420;
	egc_tup_dtype = 245;
	egc_disp_rout_id = 2024;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x01AF;
	egc_sp_wchar = 0x027B;
	egc_sp_bool = 0x02E2;
	egc_sp_uint8 = 0x01FE;
	egc_sp_uint16 = 0x02BF;
	egc_sp_uint32 = 0x029C;
	egc_sp_uint64 = 0x01D2;
	egc_sp_int8 = 0xFFFF;
	egc_sp_int16 = 0xFFFF;
	egc_sp_int32 = 0x015F;
	egc_sp_int64 = 0xFFFF;
	egc_sp_real32 = 0x034A;
	egc_sp_real64 = 0x036D;
	egc_sp_pointer = 0x0320;
	egc_sp_ref = 0x01A0;

	egc_uint8_dtype = 265;
	egc_uint16_dtype = 262;
	egc_uint32_dtype = 259;
	egc_uint64_dtype = 256;
	egc_int8_dtype = 253;
	egc_int16_dtype = 250;
	egc_int32_dtype = 247;
	egc_int64_dtype = 283;
	egc_bool_dtype = 280;
	egc_real32_dtype = 268;
	egc_char_dtype = 277;
	egc_wchar_dtype = 274;
	egc_real64_dtype = 271;
	egc_point_dtype = 286;

	egc_exception_dtype = 114;
	egc_except_emnger_dtype = 65;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "ans_save";
	egc_system_location = "/Users/RuslanFarkhutdinov/Desktop/EForms. Backend/AnsSave/EIFGENs/ans_save/W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1490794437;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 929;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "ANS_SAVE.make_and_launch";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 1058;
	egc_rcarg[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 101;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F102_1639;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F102_1640;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 88; /* ANS_SAVE */
	}
}

#ifdef __cplusplus
}
#endif
