/*
 * Code for class REFLECTOR_CONSTANTS
 */

#include "eif_eiffel.h"
#include "../E1/estructure.h"


#ifdef __cplusplus
extern "C" {
#endif

extern EIF_TYPED_VALUE F199_3052(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3053(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3054(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3055(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3056(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3057(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3058(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3059(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3060(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3061(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3062(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3063(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3064(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3065(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3066(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3067(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3068(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3069(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3070(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3071(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3072(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3073(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3074(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3075(EIF_REFERENCE);
extern EIF_TYPED_VALUE F199_3076(EIF_REFERENCE);
extern void EIF_Minit199(void);

#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

/* {REFLECTOR_CONSTANTS}.none_type */
EIF_TYPED_VALUE F199_3052 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -2L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.pointer_type */
EIF_TYPED_VALUE F199_3053 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 0L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.reference_type */
EIF_TYPED_VALUE F199_3054 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 1L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.character_8_type */
EIF_TYPED_VALUE F199_3055 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.character_type */
EIF_TYPED_VALUE F199_3056 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 2L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.boolean_type */
EIF_TYPED_VALUE F199_3057 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 3L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.integer_32_type */
EIF_TYPED_VALUE F199_3058 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.integer_type */
EIF_TYPED_VALUE F199_3059 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 4L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.real_32_type */
EIF_TYPED_VALUE F199_3060 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.real_type */
EIF_TYPED_VALUE F199_3061 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 5L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.real_64_type */
EIF_TYPED_VALUE F199_3062 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.double_type */
EIF_TYPED_VALUE F199_3063 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 6L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.expanded_type */
EIF_TYPED_VALUE F199_3064 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 7L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.bit_type */
EIF_TYPED_VALUE F199_3065 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 8L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.integer_8_type */
EIF_TYPED_VALUE F199_3066 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 9L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.integer_16_type */
EIF_TYPED_VALUE F199_3067 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 10L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.integer_64_type */
EIF_TYPED_VALUE F199_3068 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 11L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.character_32_type */
EIF_TYPED_VALUE F199_3069 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 12L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.wide_character_type */
EIF_TYPED_VALUE F199_3070 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 12L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.natural_8_type */
EIF_TYPED_VALUE F199_3071 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 13L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.natural_16_type */
EIF_TYPED_VALUE F199_3072 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 14L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.natural_32_type */
EIF_TYPED_VALUE F199_3073 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 15L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.natural_64_type */
EIF_TYPED_VALUE F199_3074 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.min_predefined_type */
EIF_TYPED_VALUE F199_3075 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) -2L);
	return r;
}

/* {REFLECTOR_CONSTANTS}.max_predefined_type */
EIF_TYPED_VALUE F199_3076 (EIF_REFERENCE Current)
{
	EIF_TYPED_VALUE r;
	r.type = SK_INT32;
	r.it_i4 = (EIF_INTEGER_32) ((EIF_INTEGER_32) 16L);
	return r;
}

void EIF_Minit199 (void)
{
	GTCX
}


#ifdef __cplusplus
}
#endif
